lib/lago/__init__.py

Allow when given both url and path to store the disk in given path
Both url and uri are part of the disk json spec
Change-Id: I5ec0290d4ab81d1ce90bf3969aa6267b33c47aee
Signed-off-by: Tolik Litovsky <tlitovsk@redhat.com>

Support storing of disk url's into given path

---

lib/lago/templates.py

Download progress

---

lib/lago/templates.py

Fixes #35
Change-Id: I13f228be25505a6392a227dca53861c884a94d69

Using posixpath.join to concatenate urls

---

lib/lago/dom_template.xml

Fixes #63
Change-Id: I472b9f398bc2dc2b4788414dde8f934f2e96a83b

Add serial pty to the domains

---

lib/lago/cmd.py

Also fixed docs of copy-to-vm
Fixes #69
Change-Id: I586b9c9774bbcf3676984e131e6558ec80a77ca2

Fixed issue with copy-from-vm

---

docs/CI.rst
docs/conf.py
docs/index.rst
docs/requires.txt

Fixed a couple warning when building the docs too
Change-Id: Id75faddcbaecd995008a75ee6d815a5f3003400c

Added CI process to the docs

---

lib/lago/__init__.py

This code will allow 2 things
Use of backing files for qcow2 mode
Allow use of two machines with one original backing file
Change-Id: I173030466ee5b90a1f2613e802086a0d6f1b9307
Signed-off-by: Tolik Litovsky <tlitovsk@redhat.com>

Adding use of backing mode for qcow2 files

---

lib/lago/cmd.py
lib/lago/utils.py
lib/lago/virt.py
setup.py
tests/functional/basic.bats

Only interactive mode for now, good enough for manual debug of the
boot process, but will have to improve it to get non-interactive mode
to be able to log the console outputs during the tests at some point.
Change-Id: Ife996f0f45004b347d5efd73d03dda8205b5fe89

Added console cli command

---

README.md

Fixes #102
Change-Id: Ida31a19900989e75abaaab240875b1d796b91fd0

docs:Added note on user home rights

---

automation/check-merged.sh
automation/check-patch.sh
automation/common.sh
docs/Env_Setup.rst
docs/index.rst

Change-Id: I5382513d53719e18ef22e7b7617c2e30b5b6b6e5

docs:Added small page with devel setup guide

---

contrib/ovirt/lib/ovirtlago/__init__.py

Change-Id: I02186db8f73c5a420f7650a406f137dfb22a5a2e

Added some extra logs to ovirt prefix _deactivate

---

contrib/ovirt/lib/ovirtlago/testlib.py

Change-Id: I5db678fcafc516cc40a0559037c11e10e5e4d631

ovirt:Fixed issue with no capabilities

---

automation/common.sh
lib/lago/brctl.py

Now you will get the return code and stdout/stderr from it in the
exception message
Change-Id: I95fdcfaa10f602213ad8936e80dcba8947153c2f

Added some extra info on brctl error

---

README.md

Change-Id: Ic4f2820fe3f66f6793136bd601e60252c7a7e1cc
Signed-off-by: Allon Mureinik <amureini@redhat.com>

README: Add reference to other EL distros

---

setup.cfg

Fixes #125
Change-Id: Iaaa8ea20c9e949a8e26bb20a2e471d0705f4c73b

Don't run flakes on rpmbuild/dist dirs

---

lib/lago/sysprep.py
tests/functional/basic.bats
tests/functional/start.bats

Fixes #94
Change-Id: Ia51a53fa4a00a3933660f675fb3b8faa4e86bd0b

Use direct libguestfs backend by default

---

lib/lago/cmd.py
tests/functional/basic.bats

Change-Id: I85493721177b5d9b16d2a2981e152cffea017430

Added the --version option

---

lib/lago/cmd.py
lib/lago/prefix.py
lib/lago/virt.py

Added --list|-l option to snapshots command

---

docs/Dev_Bootstrap.rst
docs/index.rst

Just to get started with the technologies and techniques used in lago

Added page with some resources for new devs

---

lib/lago/cmd.py
setup.py
tests/functional/basic.bats

It will cleanup (stop vms, unregister everything...) and remove the
whole prefix, it will ask for confirmation unless --yes|-y is passed
Fixes #110

Added the destroy command

---

automation/check-merged.mounts
setup.cfg
tests/functional/fixtures/ovirt.collect/scripts/generate_engine_logs.sh
tests/functional/fixtures/ovirt.collect/scripts/generate_host_logs.sh
tests/functional/fixtures/ovirt.collect/suite.yaml
tests/functional/fixtures/ovirt.deploy/nicefile
tests/functional/fixtures/ovirt.deploy/scripts/create_nicefile.sh
tests/functional/fixtures/ovirt.deploy/scripts/create_uglyfile.sh
tests/functional/fixtures/ovirt.deploy/scripts/fail.sh
tests/functional/fixtures/ovirt.deploy/suite_1host.yaml
tests/functional/fixtures/ovirt.deploy/suite_1host_fail.yaml
tests/functional/fixtures/ovirt.deploy/uglyfile
tests/functional/fixtures/ovirt.runtest/001_basic_errored_test.py
tests/functional/fixtures/ovirt.runtest/001_basic_failed_test.py
tests/functional/fixtures/ovirt.runtest/001_basic_test.py
tests/functional/fixtures/ovirt.runtest/suite.yaml
tests/functional/fixtures/snapshot/1host_1disk_list
tests/functional/fixtures/snapshot/1host_1disk_status
tests/functional/fixtures/snapshot/suite_1host_1disk.yaml
tests/functional/helpers.bash
tests/functional/ovirt.collect.bats
tests/functional/ovirt.deploy.bats
tests/functional/ovirt.runtest.bats
tests/functional/snapshot.bats

These should run only on merge an they download templates from the
template repo and might take some time

Adding some of the heavyweight functional tests

---

.gitignore
Makefile

Also, add AUTHORS to .gitignore

Add AUTHORS to 'make clean' command

---

tests/unit/lago/test_workdir.py

Change-Id: Ib4e4ae5d3a6330276627026ae58551d3aae9dfef

unit:fixed small typo

---

lago/cmd.py
lago/libvirt_utils.py
lago/virt.py
tests/functional/fixtures/basic/expected2_down_status_vm01
tests/functional/fixtures/basic/expected2_up_status_all
tests/functional/fixtures/basic/expected2_up_status_vm01
tests/functional/fixtures/basic/expected_up_status
tests/functional/fixtures/snapshot/1host_1disk_status
tests/functional/fixtures/start/expected_up_status
tests/unit/lago/test_libvirt_utils.py
tests/unit/lago/test_virt.py

Fixes #88
Change-Id: I691c2f1732d359901c5bb9cb7820a210ed165227

Now it will show the libvirt status of the domains

---

scripts/issues/create_user_stories.rb
scripts/issues/import_issues_from_github.rb
scripts/issues/remove_duplicated_user_stories.rb

Change-Id: I735e86680dab5c83f675060a22399629a3b47f1d

org:Added small scripts to manage taiga issues

---

etc/lago.d/lago.conf
lago/virt.py
tests/functional/fixtures/ovirt.collect/fancylog.log.expected
tests/functional/fixtures/ovirt.collect/fancylog2.log.expected
tests/functional/ovirt.collect.bats

Ovirt collect from live and stopped vms, and complain on the others (no guest-agent, no ssh, and running)

---

scripts/issues/create_user_stories.rb
scripts/issues/import_issues_from_github.rb
scripts/issues/remove_duplicated_user_stories.rb

Added also input for user/pass to avoid having to change the code
Change-Id: Ibb0c01aafb436c0353c2966082dbc6d16c91144c

Fixed issues management scripts

---

lago/cmd.py
tests/functional/basic.bats
tests/functional/fixtures/basic/LagoInitFile

Using LagoInitFile as default if none passed
Fixes #165

Using default init config file

---

automation/build-artifacts.packages.fc23
ovirtlago/__init__.py
ovirtlago/testlib.py
ovirtlago/virt.py

It was working before because we did not handle exceptions properly

ovirtlago:Added a wait for the engine to go up

---

scripts/version_manager.py

It was not handling correctly the line wraps
Change-Id: I7aa05584fac215a6ffaeede5826bfa0d94804316

Fixed changelog ugly formatting

---

lago/log_utils.py
lago/virt.py

Fix temporary ssh connection related issues

---

ovirtlago/merge_repos.py

Change-Id: I873aab53bfa5107340bf82cd9174c00e376f3650

reposync:Failing on existing but empty repo

---

ovirtlago/merge_repos.py

KISS method of merging the repos. Just copying all files per version.
Excluding 686 arch, nothing fancy.

Simplified merge repos

---

lago/prefix.py
lago/utils.py
tests/functional/collect.bats

It adds a timestamp to it
Fixes #11

Collect now rotates the dest dir if exists

---

lago/prefix.py
lago/utils.py
ovirtlago/__init__.py
ovirtlago/repoverify.py

* More logs
* Not hiding errors
* Better speed
* Fixed some wrong behaviors:
- not ignoring reposync errors
- not properly verifying the downloaded repos

Refactor and enhancement of reposetup flow

---

ovirtlago/__init__.py

That solves most of the issues, and it's usually faster (and better,
as it will make sure you have the latest rpms) than the verification
Change-Id: I0461f22f6f3b15852a0760985f486dfe108a49cc

Reposync first retry with clean caches

---

.gitignore

Change-Id: I9f1332277bb96a0862749994817eb666ace8727c

Added extra ignores to .gitignore

---

ovirtlago/__init__.py

Issue specified at:
https://bugzilla.redhat.com/show_bug.cgi?id=1332441
Change-Id: Ia5b46519a8c08b52da6f704d13e47b597f2e82be

Added workaround for reposync

---

lago/log_utils.py

Fixes #238
Change-Id: I9925e8ccd838669d3a9507e1ee0d773a5e35f224

log_utils:Not failing on tracedump logs

---

lago/prefix.py
lago/templates.py
lago/virt.py
ovirtlago/__init__.py

Change-Id: If4b03f9e418cfafe39d4e3f4e04a1ab7e286068c

Reformat everything to new yapf version

---

Makefile
docs/index.rst

Fixes #234
Change-Id: I0e69326dc5a32ae5bc23ad4eeb95ed89a9421d7b

Add changelog to the docs

---

ovirtlago/__init__.py

Change-Id: I4451117aac229fd6e3e55a2784b725faee87ee6a

Yet another small fix to better detect reposync issues

---

Makefile
docs/conf.py

That way it works as expected on readthedocs too
Change-Id: I4b85dfee9a9e74c390caab2b7a6c9097d310943a

Generating the docs changelog on conf.py

---

lago/log_utils.py
lago/virt.py

Fixed ssh connection issues when waiting for ssh

---

lago/virt.py

Change-Id: I3c8a76e6fa251dee83d01df845a004d3d8a2c81b

virt.VM.ssh:Use the propagation value passed

---

ovirtlago/__init__.py
ovirtlago/utils.py

That avoids using 100% cpu on ovirt serve
Fixes #41
Change-Id: I5fb098ece8ba387bac28002ac61b424f8b0c3e85

Added sleep to ovirt.serve busy loop

---

ovirtlago/__init__.py
ovirtlago/merge_repos.py

As the one from ovirtlago was removed
Fixes #252
Change-Id: Ic1e008b0b61bf39d019e7022ea1b378b2ff65dfe

Using main lago run_command

---

lago/cmd.py
lago/prefix.py
lago/virt.py
tests/functional/fixtures/basic/repo_store/local_tests_repo:lago_functional_tests:v1.hash

Also refactored a bit the image and disk handling code.
Change-Id: I286c275a17ae9116fc606d2e2bdc92bccf62cf64

Added possibility to use env vars on disk path and url

---

lago/prefix.py

Change-Id: I49ad846d14b12fc0813100d3469eeb22f305ca89

Expanding any vars on any url

---

.style.yapf
lago/prefix.py
lago/templates.py
lago/virt.py
ovirtlago/__init__.py
test-requires.txt

Yafp changed it's version again and the way it worked
Change-Id: I0c909c8e18505a3375bc9adc0912c06b98e0567c

Yapf fixes

---

lago/plugins/vm.py

Change-Id: Ie8abaf613bce6cf3c71a234f5472c21b25f87527

Allow copying dirs in the vm

---

tests/functional/collect.bats
tests/functional/ovirt.collect.bats
tests/functional/snapshot.bats

Change-Id: Ib05053e7fcc897e0d894bcaaac848b4a0310da1e

func:Added extra syncs to make sure the disk is written

---

ovirtlago/virt.py

Change-Id: I5af090be7b150293201fc7298bc9c8a76903db51

Fix typo on warning message

---

lago/plugins/__init__.py

Added a callback function to handle import exception

---

lago/log_utils.py

Hide import error when using old versions of stevedore.

---

automation/common.sh
lago/vm.py
setup.cfg

Not sure if this [fix](https://github.com/lago-project/lago/blob/master/automation/common.sh#L116) is still required.

Search for kvm executable too

---

ovirtlago/testlib.py
ovirtlago/virt.py

Specifically refer to v3 API for now.
Next item would be to actually add v4 API.

Prep for oVirt v4 API

---

docs/Installation.rst
docs/conf.py

closes: https://github.com/lago-project/lago/issues/195

[docs] add epel to installation guide for el7

---

requirements.txt

Added pyxdg and configparser to requirements.txt

---

ovirtlago/virt.py
setup.cfg

Change-Id: I9f0305681cabdcd87a079806a60fecdd1e5ac5be
Signed-off-by: Yedidyah Bar David didi@redhat.com

Add vm-type ovirt-he-host

---

docs/Configuration.rst
docs/index.rst

Adding configuration section to the docs. Mainly address changes from https://github.com/lago-project/lago/pull/324.

[docs] lago.conf customization

---

ovirtlago/reposetup.py

Fix reposync - use 'continue', not 'return'

---

lago/dom_template.xml
lago/sysprep.py
lago/vm.py

1. Remove the grub boot menu in virt-sysprep phase
2. Remove the QEMU boot menu in domain template XML
3. Wait 5 seconds till the VM is potentially ready to
receive SSH connections

Reduce boot time

---

ovirtlago/testlib.py

Tests which are stopped by raising SkipTest exception, will be logged to stdout. Until now they were only logged in the test report XML.
Example output from OST:
```bash
* SKIPPED: Exported domain generation not supported yet
....
* SKIPPED: 
```
side-note: another problem I noticed while handling this is that if a none-SkipTest exception was thrown, subsequent SkipTest exceptions will loose their description, in stdout they will appear only with ``SKIPPED: ``. I think the reason is mishandling of the exceptions in  [test_sequnce_gen](https://github.com/lago-project/lago/blob/master/ovirtlago/testlib.py#L130-#L148) function. I'll address that in a different PR.

ovirtlago: log skipped tests to stdout

---

lago/virt.py

This will busy-wait until the network is created
for at most 10 seconds. At the minimum, it will
exit after the first check the network is active,
without sleeping.

Check network is active after creation

---

lago/sysprep.py
lago/vm.py

1. Properly inject SSH key
2. No need to enforce SElinux (it is enforced already)

Small sysprep fixes

---

lago/net_nat_template.xml
lago/virt.py

Now it uses the same subnet as IPv4.

Fix IPv6 subnet allocation.

---

ovirtlago/testlib.py

Added testlib tests testing for method to value equality.
The primary motivation behind this is to be able to receive informative assertion errors for failed tests, and to be able to skip the step of passing anonymous (or otherwise) functions as test input.

added test_equals* tests to testlib

---

lago/cmd.py
lago/dom_template.xml
lago/plugins/vm.py
lago/vm.py
tests/functional/common.bash
tests/functional/fixtures/basic/expected2_down_status_vm01
tests/functional/fixtures/basic/expected2_up_status_all
tests/functional/fixtures/basic/expected2_up_status_vm01
tests/functional/fixtures/basic/expected_up_status
tests/functional/fixtures/snapshot/1host_1disk_status
tests/functional/fixtures/start/expected_up_status
tests/functional/fixtures/status/prefix_skel/expected.json
tests/functional/fixtures/status/prefix_skel/expected.yaml

I don't see why we need VNC. We get fine with SSH and console.

Remove the video device.

---

ovirtlago/reposetup.py

docs: reposetup.merge sphinix formatting fix

---

Makefile
lago/cmd.py
lago/plugins/__init__.py
lago_template_repo/__init__.py
ovirtlago/cmd.py
ovirtlago/reposetup.py
scripts/version_manager.py
tests/functional/fixtures/ovirt.runtest/001_basic_errored_test.py
tests/functional/fixtures/ovirt.runtest/001_basic_failed_test.py
tests/functional/fixtures/ovirt.runtest/001_basic_test.py

Currently, the code still uses constructs incompatible with Python 3, and so we should run it with the python2 binary.

Use python2 explicitly.

---

docs/requires.txt

see:
https://github.com/sphinx-doc/sphinx/issues/3597

docs: pin sphinx version

---

docs/LagoInitFile.rst
docs/index.rst

Complementary to https://github.com/lago-project/lago/pull/470

[docs] Add supported CPU parameters

---

test-requires.txt

This might require us to update the yapf version locally once in a
while, but we will enjoy new features/bug fixes.

tests: don't pin yapf version

---

lago/plugins/output.py
ovirtlago/cmd.py
ovirtlago/virt.py

1. Format the output with format plugins.
2. Adding url to the web ui.
3. Adding engine's web ui username and password.
4. Auto detect all the items from api.system_service.summary (hosts,
vms, sds, users)

Improve lago ovirt status

---

lago.spec.in

rpm-spec: Don't fail if group "lago" already exist

---

lago/sysprep.py

Using the SDK I see random failures on boot to acquire IP via DHCP,
looking at the logs, it looks like the order of keys and values in the
generated ifcfg-eth* devices is different than successful runs in the
CLI. Also I see failures when the 'TYPE' parameter is first, while
successes when 'HWADDR' is first. This in all might be vodoo tales, but
it might solve this issue, before digging deeper into what is
wrong with NetworkManager(the logs don't reveal much currently - just
that dhclient start, but it doesn't send any requests).
If this is only vodoo indeed, this patch can't harm(just ensures we use
the same order).

sysprep: ensure el based ifcfg files are created consistently

---

tests/functional-sdk/test_sdk_sanity.py
tox-sdk.ini

1. Stop after first failure.
2. Increase SSH timeout.
3. Collect several more artifacts.
4. Don't archive images in exported-artifacts.

tests: functional tests improvements

---

lago/sdk.py
lago/sdk_utils.py
tests/functional-sdk/test_sdk_sanity.py
tests/unit/lago/test_sdk.py

sdk: Allow to load an existing environment

---

.gitignore
automation/check-patch.packages
automation/check-patch.packages.el7
docs/SDK.rst
docs/conf.py
docs/docs-requires.txt
docs/examples/lago_sdk_one_vm_one_net.ipynb
docs/index.rst
tox.ini

1. Add SDK.rst docs.
2. Add IPython Notebook example - those can be viewed in the docs, or
directly from GitHub.

docs: add sdk

---

docs/conf.py
docs/docs-requires.txt

docs: fix ipython lexer warning

---

docs/SDK.rst

docs: SDK.rst minor fixes

---

docs/Installation.rst
docs/SDK.rst

1. Add the install script section.
2. Try to make the instructions 'copy and paste' friendly.
3. Add troubleshooting/FAQ section.

docs: Installation notes enhancements

---

README.rst
docs/CPU.rst
docs/LagoInitFile.rst
docs/Lago_Examples.rst
docs/Templates.rst
docs/index.rst

1. Added templates section
2. Improved LagoInitFile spec section - still has work of course.
3. Update examples
4. Move CPU to a different (and later) section.
5. Remove to-do directive from README.md

docs: various improvements 

---

tests/functional-sdk/test_sdk_sanity.py

tests: add metadata check

---

.gitignore

gitignore: add flake8.txt

---

tests/functional-sdk/conftest.py
tests/functional-sdk/test_sdk_sanity.py

tests: add el6 test on check_merged

---

tests/functional-sdk/test_sdk_sanity.py

Will be available in:
exported-artifacts/test_results/functional-sdk/test_results_sdk/test_sdk_sanity/systemd-analyze-<VM_NAME>.txt
or under test_results if running locally:
```bash
$ pytest -vvv -s /tests/functional-sdk
```
fixes: https://github.com/lago-project/lago/issues/569

tests: run systemd-analyze blame after each run

---

tests/functional-sdk/test_sdk_sanity.py

Part of the effort to solve https://github.com/lago-project/lago/issues/580 as I can't replicate it at the moment.

tests: add collect from vm

---

setup.cfg

Mainly to format nicely on PyPi

setup.cfg: metadata fixes

---

docs/conf.py
lago/subnet_lease.py

- Adding netaddr to docs conf
- Adding missing docstrings do subent_lease.is_leasable_subnet

Adding netaddr to docs conf

---

docs/Installation.rst

docs: change yum -> dnf for fedora

---

docs/BUILD.rst
docs/LagoInitFile.rst
docs/index.rst

closes https://github.com/lago-project/lago/issues/509

Adding docs about the build section

---

lago/prefix.py

1. If the disk is a layer and the path to his backing
file is correct, do nothing.
2. Avoid endless recursion when the disk and its backing file
has the same name.
3. Safely parse the name and the version of the backing file.
Raise exception if the format of the backing file is not name:version.

export: Backing file resolution fixes

---

lago/cmd.py
tests/functional/basic.bats

1. Fixed lago list to print the available prefixes in a workidir.
2. Fixed the docstrings.
3. Added cli functional test.

Fix lago list

---

lago/providers/libvirt/vm.py

Print an informative message when qemu doesn't have
permissions to the storage files of the VMs.

qemu: raise informative exception on missing permissions

---

tests/functional-sdk/conftest.py

tests: add fc26 to SDK functional tests

---

lago.spec.in
lago/prefix.py
lago/subnet_lease.py
requirements.txt
tests/unit/lago/test_subnet_lease.py

Free the used subnet when destroying the prefix.
fixes: https://github.com/lago-project/lago/issues/614
fixes: https://github.com/lago-project/lago/issues/599

subnets: free on destroy

---

lago/export.py
lago/log_utils.py
lago/providers/libvirt/network.py
lago/providers/libvirt/vm.py
lago/sdk.py
lago/service.py

Shortens the lines and compatible with Python 3.

Backport Python3 super constructor to the codebase

---

docs/Templates.rst

Others changes just adds new lines(auto formatter).

docs: add fc26 to template list

---

automation/common.sh

automation: install with pip package-by-package

---

lago/ssh.py

Change-Id: I63583d08f29d054f73c5b65ce02b728efb29e7ca
Signed-off-by: Yedidyah Bar David <didi@redhat.com>

Log running ssh_script

---

lago/plugins/__init__.py
lago/workdir.py
tests/unit/lago/test_workdir.py

Catching "Exception" can mask other errors.

workdir: Narrow except in is_workdir

---

lago/providers/libvirt/cpu.py
tests/unit/lago/providers/libvirt/test_cpu.py

Logic:
If there's >1 vCPU:
2 vCPUs - 2 NUMA nodes, each has 1 vCPU
4 vCPUS - 2 NUMA nodes, each has 1 vCPU
Otherwise:
If num of vCPUs (N) divisible by 4:
N/4 NUMA nodes, each has 4 vCPUs
If num of vCPUs divisible by 2:
N/2 NUMA nodes, each has 2 vCPUs
Otherwise,
N NUMA nodes, each has 1 vCPU.
Tested with 1 - 6 vCPUs.

Add NUMA awareness to Lago.

---

etc/sudo/lago

- Require for changing the permissions of the disks
after taking a snapshot.
- A long term solution should be implemented using polkit.

Allow running "chmod" as qemu user

---

lago/providers/libvirt/vm.py

Specifically, enable IO threads and network multi-q for L1 VMs.

On Fedora, use more advanced features of qemu-kvm.

---

Makefile
automation/build-container.sh
container/Makefile
container/README.rst
container/build-lago-container.sh
container/el7-systemd-lago/Dockerfile.in
container/el7-systemd-lago/deploy.sh
container/el7-systemd-libvirt/Dockerfile.in
container/el7-systemd/Dockerfile
container/scripts/lago.sh
container/scripts/run-lago-container.sh

The lago container is based on el7 container running systemd

Build Lago container

---

docs/Installation.rst

Signed-off-by: Emil Natan <ena@redhat.com>

Fix installation doc - sudo and shell redirect

---

lago/workdir.py
tests/unit/lago/test_workdir.py

Signed-off-by: Galit <grosenth@redhat.com>

Show message when prefix already exists

---

lago/virt.py

Signed-off-by: Galit <grosenth@redhat.com>

Meaningful message when there is Unknown VM type

---

scripts/version_manager.py

When creating a shallow clone of a repo, the history is being
truncated. This behaviour cause the first commit in the repo to have
a parent, but the metadata of parent isn't available.
We need this change since "read the docs" moved to use shallow git
clones.

version_manager: Support shallow git clones

---

tests/functional-sdk/conftest.py

func-tests: Update Centos image to 7.6

---

automation.yaml

Signed-off-by: Marcin Sobczyk <msobczyk@redhat.com>

ci: Switch to stdci v2

---

scripts/version_manager.py

Signed-off-by: Marcin Sobczyk <msobczyk@redhat.com>

ci: Fix bytes x string issue in 'version_manager'
