lago-project/lago

lib/lago/templates.py

Since download can be slow and long, add simple
progress report - percentage and Kilobytes downloaded.

Progress report for template download

---

scripts/version_manager.py

Now it will group together the merge commits in the changelog and count
only the 'first parents' when doing the version calculation.
Change-Id: Ib77dee2346c2e357fb32a9a5fd3439b37617b866

Fixed the version generation

---

lib/lago/cmd.py
scripts/version_manager.py

Before it was not using the prefix path, but the prefix instance, and
thus, failing

Fix the cleanup on init failure

---

lib/lago/virt.py

This patch will allow long booting machines to operate too
Like the ovirt engine appliance first boot
Change-Id: Id85f29b8fdf026e2910c326f2e2c9dce82f467aa
Signed-off-by: Tolik Litovsky <tlitovsk@redhat.com>

Adding the ssh timout to the spec

---

lib/lago/__init__.py
lib/lago/virt.py

This patch will allow the ovirt contrib plugin to handle the ova disk properly
It will be able to find the correct rootfs in the correct disk order

Ova ovirt support

---

automation/check-patch.sh

Now it compares the current commit with it's first parent, instead of
just looking for changes in the current commit (that worked when not
using merge commits).
Change-Id: I9614bec1e931c35fbf9298db69cc6c58ffa13b9f

Fix changed file detection

---

automation/check-patch.packages
docs/conf.py
lago.spec.in
lib/lago/virt.py

That allows using hosts that don't have sftp server installed, like
the small cirros/busybox images that use dropbear for ssh
Fixes #79
Change-Id: I3734ad048953a2a40f7eb0d4b86c0b751ac35f1d

Moving from sftp to scp for copy to/from vms

---

contrib/ovirt/lib/ovirtlago/__init__.py
contrib/ovirt/lib/ovirtlago/virt.py

This is combined from two patches
Node VM that avoid ssh connection and artefact collection
And avoiding the SSH connection when no scripts exist
Change-Id: I45df7d5ac92d68526ff5a034471aef73399a61af
Signed-off-by: Tolik Litovsky <tlitovsk@redhat.com>

Add ovirt Node VM support

---

README.md

Migrated from https://gerrit.ovirt.org/#/c/51200/

Adding clarification on the default images location

---

contrib/ovirt/lib/ovirtlago/__init__.py

Change-Id: I49cf26295736286fc5538af1c3ea8049b111319b

Fix wrong import of TaskLogNosePlugin

---

.gitignore

Add rpmbuild and lago-egg.info to .gitignore

Add 'rpmbuild' and 'lago.egg-info' to .gitignore

---

lago/cmd.py
ovirtlago/cmd.py
tests/functional/basic.bats

This allows to explicitly override the automatic discovery of the
prefix path it should be working on
Change-Id: If440b6b5d7d8cf457abe7bf4727fa405fc692c1a

Added --prefix-path option to the lago command

---

lago/cmd.py
tests/functional/basic.bats
tests/functional/helpers.bash

Also moved to use the python stdlib warnings module, that allows us to
use deprecation warnings and handle them properly.
Change-Id: Ib2891696d6c04b2d9f5567413b769d94c46db7c9

Added ignore-warnings option

---

ovirtlago/merge_repos.py

For some reason (unsuccesful downloads?) I got empty RPM files.
They were merged with other (good) files and I had those as RPMs.
Obviously, they failed to install.
The search for the RPMs now ignores such files and thus merges only REAL files.

Ignore zero sized RPM files when merging repos.

---

lago/dom_template.xml

The less devices the better. 
(I'm wondering what else we can remove, move to virtio, etc.)

Remove the memory balloon device. We don't use it.

---

etc/lago.d/lago.conf
lago/config.py

That way if we introduce a new conf value and the local conf file was
modified, an upgrade will not make lago throw 'missing key' error, but
get the default from the defaults in the code itself
Fixes #187
Change-Id: I9d20f91a3789a9068a0bafdecfb6e1e974219a01

Added config defaults to code

---

lago/cmd.py
tests/functional/basic.bats

That will set the newly created prefix as the current one

Added --set-current option to init subcommand

---

lago/sysprep.py

For example, when bootstrapping a disk
Change-Id: I614cb9e1aee96f0008bb5d013492c15c5cf0da51

Showing extra logs on sysprep errors

---

lago/sysprep.py

Change-Id: I0a44e5551b10b71362cec1c2698900463f00c3fe

Fixed string interpolation when showing sysprep error

---

lago/cmd.py
lago/virt.py
tests/unit/lago/test_virt.py

Alive means that it's running, defined that it's defined in libvirt,
but on any other state.
Fixes #203
Change-Id: I1b1d1e06e67eb6ed2b978fc3762c7b4096868a4e

Differentiate alive and defined VM

---

automation/check-patch.packages
automation/check-patch.packages.fc23
ovirtlago/repoverify.py

Now it's behaving as reposync, matching both the name and
name+version+arch when filtering in and out packages.
Change-Id: I88266d01e8980b240b9fa0ad65efc836d11cb1a5

Fixed repoverify not behaving like reposync

---

ovirtlago/merge_repos.py

If the repos dir already existed, the reposetup log would show error
because the exception was not being cleared from the sys.exc_info
stack before starting the log task
Change-Id: Icb599df0d96f1efe330b824a973bc96e2dccf693

Fixed wrong error log on reposetup

---

lago/prefix.py
lago/utils.py
tests/functional/fixtures/deploy/suite_1host.yaml

Now you can use variables on the deploy scripts paths, and some vars are added to allow relocatable prefixes

Add prefix env vars

---

lago/cmd.py

That allows specifying the path of the deploy scripts relative to the
initfile used
Change-Id: Ibc9e24f7ad9f0de13d8dec074ee87d9a16a66c4b

Added LAGO_INITFILE_PATH env var when running init

---

.gitignore

'cscope.out' and 'tags' are both generated by tools that help navigating
Python codebase (pycscope and ctags respectively) and should be ignored
by git.

Add tags and cscope.out to gitignore

---

lago/prefix.py

As noted in https://github.com/lago-project/lago/issues/36 so far lago will happily attempt to init a prefix 
even in the case the domain name wasn't provided (is empty string). If such a domain references a network, attempt to start such a network will subsequently end up with an exception in the form similar to the one below:
```
Error occured, aborting
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 691, in main
cli_plugins[args.verb].do_run(args)
File "/usr/lib/python2.7/site-packages/lago/plugins/cli.py", line 180, in do_run
self._do_run(**vars(args))
File "/usr/lib/python2.7/site-packages/lago/utils.py", line 584, in wrapper
return func(*args, **kwargs)
File "/usr/lib/python2.7/site-packages/lago/utils.py", line 595, in wrapper
return …
```

Perform domain name check when creating mapping entry for the given network (part of #36)

---

README.rst

Instead of making the user guess which OSes are still supported.
Change-Id: I86fb57897180656cf51b890af0dd6bfe8594c7a9
Signed-off-by: Yedidyah Bar David <didi@redhat.com>

docs: Link to jenkins search result

---

README.rst

3.5 is obsolete, basic_suite_3.5 does not exist
Change-Id: I29e07eb91ae2da9020751f0a73bbcf3f44c126c8
Signed-off-by: Yedidyah Bar David <didi@redhat.com>

docs: refer to ovirt 3.6

---

lago/prefix.py

This is a followup / improvement of https://github.com/lago-project/lago/commit/5339d06d72eecf3b155ac35f5aa8b79a38f96d22 in the sense that if empty domain
name was specified in the Lago's configuration yaml / json file, the prefix initialization
will abandon sooner (not already in the moment we attempt to start network for such
an invalid domain, but rather immediately after prefix initialization - in the stage of
preparing vm images for the domain)
Fixes: #36#issuecomment-221348959
Please review.
Thank you, Jan

Detect (and report) any empty domain name possibly found in the Lago's configuration file sooner

---

ovirtlago/virt.py

Take 2 of trying to add /var/log/sanlock.log to the log collection our the VDSM hosts.

Added /var/log/sanlock.log to the log collection from hosts

---

etc/lago.d/lago.conf
lago/config.py
lago/libvirt_utils.py

Previously, lago could not work with libvirt that required auth. This
can be problematic for people working with projects that do use
authentication in libvirt, one example being VDMS.
We therefore allow setting of libvirt username and password in
lago.conf, and use these values to authenticate. Default values are
empty, therefore not expecting any form of authentication.

libvirt: add auth

---

ovirtlago/reposetup.py

Added error logging on reposync retry error.
If something prevent the reposync to complete while
running in jenkins it becomes hard to understand what failed
without having the output of the reposync command.
This patch add stdout and stderr from reposync command
to be printed before aborting the sync.
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>

reposetup: be more verbose on reposync failure

---

lago/plugins/output.py
setup.cfg

The output of this formatter is not
nested text as in yaml and json, and thus
grep friendly.
The outpust looks the same as a list of
file paths, but instead of files the path
consist of the env's attributes.

Added flat output formatter

---

lago/net_nat_template.xml
lago/utils.py
lago/virt.py
lago/vm.py

This commit adds both IPv6 (via DHCP DUID-LL) and DNS support to Lago.
- To add a DNS domain name, use dns_domain_name=example.com to the spec.
- IPv6 is added automatically.
Currently, it is using DUID-LL which means that in order
to get an address, run 'dhclient -6 -D LL' in the domain.
ovirt-system-tests will be enhanced to use the DNS support later on.
Tested with 3.6, 4.0, master.

Add DNS and IPv6 support

---

ovirtlago/virt.py

wait parameter should had to be set to true
in order for any code to be executed in '_get_api',
so it is not needed.
Removed engine's service check in order to
support a situation when we can't check for the
service stauts, but https connection is available.
I think that there is a sense in trying to request
the api within a time window, instead of giving up
on first failure, So I kept the request inside
'assert_true_within_short'.
I had to remove the 'or' condition, otherwise
if '_create_api()' returns false, the condition will
be evaluated to true, which in turn will break the
loop of 'assert_true_within'. Eventually we will end
up without api object.

Removed redundant checks when getting ovirt api

---

lago/dom_template.xml
lago/vm.py

1. Removed the USB controller - and added virtio-SCSI controller
with a single dedicated IO thread assigned to it.
2. Removed the bootmenu - did not see a need for it.
3. If a disk begins with sd (for example, 'sda') - assume it's SCSI.
4. Unconditionally add 'discard' support. It works for IDE, virtio-scsi.
It works (though does nothing) with virtio-blk.
Tested by converting some ovirt-system-tests to use sdX drives.
By running 'fstrim' inside the guests saw a good reduction in size of disks.
Note: the root disk cannot be virtio-scsi - requires a change in the lago-image.

virtio-scsi support in Lago

---

lago/vm.py

Apparently, when using SCSI disks, you can't trust the order
UDEV will see them and enumarate them.
The only correct way is use /dev/disk/by-id/...
This adds a serial number to the disk, to make it possible.
Use /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_2 for the 1st SCSI disk, etc.

Add serial number to disks.

---

lago/dom_template.xml

After removing the boot menu in
af1c52d679634180b7468e1a69ac5ea218c74fc1
We experinced failures when running check-patch
locally on our laptops. The tests were failed
on ssh timeout, which caused by a faulty network
configuraion of the vm (running ip addr flush dev eth0;
ifup eth0; inside the vm solved the network issue).
Still have to investigate how does the 'boot menu' relates
to the network configuration, but for now this patch fix
the problem.

Adding boot menu

---

lago/virt.py
ovirtlago/virt.py

Added a function to detect the host CPU (that libvirt knows about).
Added a function that calculates the ovirt CPU family level.
This will later be used in ovirt-system-tests to set cluster
CPU type.
Tested with Haswell and Broadwell CPUs, on master
and hosted-engine ovirt-system-tests.

Add host CPU model detection

---

lago/plugins/vm.py

Since most of the VMs are EL7, more likely it'll be qemu-guest-agent
than qemu-ga. Saves an SSH call...

Replace the order between qemu-ga and qemu-guest-agent.

---

ovirtlago/testlib.py

This is more useful than having it copied around in multiple tests.
Just a handy function.
After it'll be included in a released Lago, will convert
ovirt-system-tests to use it.

Moving over get_prefixed_name() to ovirtlago/testlib

---

docs/Installation.rst

Docs: setting up libvirt and user permissions
are needed for any Lago run, not just oVirt.
Signed-off-by: Eyal Edri <eedri@redhat.com>

added missing libvirt & user permissions info

---

README.rst
docs/README.rst

Before the README file contained all the info
from the docs, but since we broke up the docs
into smaller sections, it is now pointing to
an index file without any info.
Adding initial content now which should be
extended in the future to include more info
on the project, and also link to readthedocs.
Signed-off-by: Eyal Edri <eedri@redhat.com>

restore meaningfull README file

---

ovirtlago/__init__.py

The fact that a test fail should not stop the tests.
There is value in getting additional coverage, for two reasons:
1. You can find more regressions.
2. If the failure is unrelated to your patch, it gives more assurance in your patch.
Tested with a failure in DirectLUN test - the other tests continue well.
```
@ Run test: 004_basic_sanity.py: 
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
* Collect artifacts: 
* Collect artifacts: ERROR (in 0:00:03)
@ Run test: 004_basic_sanity.py: ERROR (in 0:01:30)
```

Continue testing on test failures.

---

lago/plugins/vm.py
lago/ssh.py

The the current 'wait_for_ssh' method is based on TCP timeout (the default ssh timeout in lago is 10 sec)
when the host is booting, while it doesn't get an IP the timeout is really 10 sec,
but between the time it gets it's IP to the time it opens port 22 the timeout is 0.
So, if one of my vms need more time to open port 22 and start sshd, it might fail after 50 retries.
This fix focus on the maximal 'wait-time' Lago will wait until the host can be reached,
instead of the number of retries, that may vary with different OS.
Signed-off-by: Ido Rosenzwig <irosenzw@redhat.com>

Changing the ssh connection waiting method

---

lago.spec.in
setup.cfg

When using `pip install ~/src/lago` as a normal user, I encountered an error:
> pip install ~/src/lago
> Processing ./lago
> Collecting enum (from lago===0.22.6)
> Collecting file-magic (from lago===0.22.6)
> Collecting guestfs (from lago===0.22.6)
> [...]
>     byte-compiling /home/lilou/.venv/lago/lib/python2.7/site-packages/lago/ssh.py to ssh.pyc
>     running install_data
>     creating /etc/lago.d
>     error: could not create '/etc/lago.d': Permission denied
By the way, it seems to me that the pip package should not install `/etc/{sudoers.d,polkit-1,firewalld}/`: lago can run without `firewalld`, `pip` won't install `firewalld`.

Allow non-root users to install Lago using pip

---

lago.spec.in

closes: https://github.com/lago-project/lago/issues/173

Update fedora>23 to use python2-pbr

---

lago/cmd.py

1. On some versions of rhel pbr 1.10.0 and stevedore 1.1.0
are the only versions availble. While stevedore 1.1.0
require pbr<1, it can also work with pbr 1.10.0 (tested
on my system). Added an exception handling in order to
bypass the requirements.
2. Changed the way we check for lago's version to suit
the change in [1].
example of the error:
```
traceback (most recent call last):
File "/usr/bin/lago", line 10, in <module>
sys.exit(main())
File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 659, in main
parser = create_parser(cli_plugins=cli_plugins, out_plugins=out_plugins)
File "/usr/lib/python2.7/site-packages/lago/cmd.py", line 598, in create_parser
pkg_info = pkg_resources.require("lago")[0]
File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 943, in require …
```

Allow using lago on systems which runs setevedore 1.1.0

---

lago/utils.py

Makes the generate-config output more readable.

Print help lines before parameters in generate-config cmd

---

tests/functional/common.bash

ATM, only thing it tests is if it outputs the help.

Add 'generate-config' verb to functional tests list

---

lago/cmd.py

If a host name for a shell command is not found, try to look for it
based on its suffix. This allows 'lagocli shell engine' to work,
for example, instead of 'lagocli shell lago-basic-suite-master-engine'

For ease of use, connect to a host even if only the suffix is given.

---

lago/vm.py

More importantly, by default, the call will not freeze the FS.
There is no reason to do it, for two reasons:
1. We open the FS in read-only - so no corruption can happen.
2. The system is quite stable - we already passed whatever
test we passed or failed - all logs are in the system already
(especially as in ovirt-system-tests we complete the suite after
failure)
This may prevent issues when the hosts are disconnected due to a
long freeze

Switch to optional freeze the FS before logs extraction.

---

lago/cmd.py

1. Moved deps checking into a function which runs
after the setup of the logger.
2. Minimized the scope of 'except' to catch 'ContextualVersionConflict'
(required only for the 'stevedore' fix:
1e3ebe13fb78f3bdffd95f96b92d6f66b4636fb4).
fix: https://github.com/lago-project/lago/issues/354
part of: https://github.com/lago-project/lago/pull/352

Fixed exception handling when checking for deps

---

lago/dom_template.xml
lago/vm.py

Not all hosts use virtio-SCSI. No need to create
the SCSI controller if there are not virtio-scsi
disks in the VM definition.

Create the SCSI controller only if needed.

---

ovirtlago/__init__.py
ovirtlago/reposetup.py

Until now we tried deducing the RPM name in reposync errors
from the line printing 'no more mirrors to try', however in the BZ
1399235, it is actually the rpm spec file 'Release' parameter that
is printed.
This could have been due to a change in yum/yum-utils, or we are
now seeing a different error.
This patch attempts to make the 'reposync' stage more robust and
verbose:
1. New regex lookups were added according to the BZ, the old regex
(probably due to yum/yum-utils changes) is looking for a different
error and also sometimes matched incorrect RPM names(which starting with
'^M' sequence).
It attempts to look RPM names according to the fedora guidelines:
https://fedoraproject.org/wiki/How_to_create_an_RPM_package
2. Defected packages lookup will be done inside python instead
of GNU find …

make reposync more verbose and fix bz 1399235

---

ovirtlago/testlib.py

The 'ovirt-capabilities' metadata always returned
false because the new returned set from 'union'
operation was not assigned.

ovirtlago: fix bug in capabilities

---

automation/check-merged.mounts
automation/check-merged.sh
automation/check-patch.mounts
automation/check-patch.sh
automation/common.sh
tests/functional/basic.bats
tests/functional/collect.bats
tests/functional/deploy.bats
tests/functional/ovirt.collect.bats
tests/functional/ovirt.runtest.bats
tests/functional/snapshot.bats
tests/functional/start.bats

1. Fix for #389
2. Configure libguestfs tmp dir to be /dev/shm for potential
speed improvements in the functional tests.
3. Ensure /dev/kvm device exists under mock(used by libguestfs)
4. Remove export LIBGUESTFS_DEBUG=1 LIBGUESTFS_TRACE=1 from functional
tests

automation: configure KVM and libguestfs parameters

---

ovirtlago/virt.py

Apparently, it may take a bit more time for APIv4 to be really ready
just after Engine starts - as it calls the SSO process.
Give it a chance by iteration over the test() command few times.

Fix oVirt APIv4 creation

---

lago/cmd.py
lago/plugins/vm.py
lago/prefix.py
lago/ssh.py
lago/vm.py
ovirtlago/cmd.py
ovirtlago/testlib.py
ovirtlago/virt.py
tests/functional/collect.bats

1. Change the default method for extracting files with 'lago collect'
command to SCP. Extracting using libguestfs becomes the fallback
when SSH is not available.
2. Introduce a new option '--no-skip' which will force not skipping
missing paths. If used it will raise a ``ExtractPathNoPathError``
exception if any of the paths does not exist on the host.
3. Drop the option of using fsFreeze/FsThaw when extracting
files with libguestfs.
4. Redirect 'lago ovirt collect' to 'lago collect' and issue a warning
if used directly.
5. Change the functional tests accordingly.
Some more notes:
1. As SCP becomes the first priority - there is no point in keeping the fsFreeze/fsThaw method, because it requires the guest-agent to be running, but we are only able to ensure it is running with SSH(see …

Refactor collect command to use SCP

---

ovirtlago/testlib.py

This patch removes all exception handling that was done
in 'test_seqeuence_gen', instead letting nose handle the
exceptions. Also removing 'continue_on_failure' decorator
which was unused.
Some more details:
1. In OST we call ```test_sequence_gen```  to generate the tests for nose.
2. In the current implementation, which its commits go back to [bitbucket times](https://bitbucket.org/ydary/ovirt-testing-framework/commits/af62d0504dd490602892e6b167f8ef69d06a3338#Ltests/testlib.pyT52), I couldn't find any documents what it is meant to do.
3. What I think it is trying to do:
If you add an attribute ``continue_on_failure`` to any test, it would not stop when exception is raised. On the other side, if an exception occurred it would raise a SkipTest on all tests afterwards.
But, this has few …

ovirtlago: drop exception handling in test_sequence_gen

---

lago/sysprep.py

Until now we always used 'direct' in virt-sysprep command.
With this change:
1. 'direct' will be used if LIBGUESTFS_BACKEND is not set.
2. 'LIBGUESTFS_BACKEND' value will be used if set.
According to the [docs](http://libguestfs.org/guestfs.3.html#backend) libguestfs is usally compiled with the 'direct' backend, but not always. So setting this to 'direct' unless the user explicitly asked something else should be safe.

use LIBGUESTFS_BACKEND variable if set

---

lago/sysprep.py

https://github.com/lago-project/lago/pull/395 added an enhancement of using  virt-sysprep 'ssh-inject'. Turns out this feature is only available in libguestfs >v1.30, until we sort out how that version is consumed on el7.2(or if we drop support for el7.2), I suggest to revert it. Later we can reapply this and also add the version requirement to the spec file.

Revert usage of 'ssh-inject' in sysprep

---

lago/plugins/vm.py
lago/virt.py

Now that we've started using multiple networks, it's nice to be able to get all IPs of a VM.
Apparently, there's a strange scheme for the names:
The first is <name>, the others are <name-ethX> .
We should probably change it, but regardless, for now this allows getting all IPs.
Something like:
lago-basic-suite-master-engine: ips: [u'192.168.200.3', u'192.168.202.3']
And it'll be used in ovirt-system-tests later, something like:
def _get_host_all_ips(prefix, host_name):
return prefix.virt_env.get_vm(host_name).all_ips()

Add a function to get all the IPs of a VM

---

lago/dom_template.xml
lago/virt.py
lago/vm.py
ovirtlago/virt.py

CPU model for Lago VMs is passed through from the host and the cluster CPU
family is set based on that CPU model.  This approach has some problems:
- CPU model is set according to the host CPU, which means that the tests are
not always run in the same environment.
- The environment deployment may fail due to invalid CPU family of the cluster.
Although the family corresponds to the host CPU, kernel may remove some CPU
flags in nested virtual machines (when the Lago host is actually a VM).  Then
some CPU flags required for the given CPU family (such as Haswell-NoTSX) may
be missing in the Lago virtual machines.
- Newer CPU families are not recognized until the table of CPU families is
updated.
This patch fixes the problems by selecting a minimum reasonable CPU model for
the given hardware …

Choose the same CPU models

---

lago.spec.in

py2_build and py2_install macros are missing on RHEL/CentOS.
Let's define them so that the package can be built on those platforms.

Make the package build on RHEL/CentOS

---

lago/vm.py
tests/functional/common.bash

When 'LAGO__START__WAIT_SUSPEND' environment variable value
is set to a float or integer, each domain will be started
in 'paused' mode(CPU halted), and it will be resumed
after waiting for the value set.
This is currently not added to the CLI, as hopefully
this workaround will be removed once the BZ is fixed.
bug-url: https://bugzilla.redhat.com/show_bug.cgi?id=1411025

workaround for cirros images not getting ip on boot

---

lago/cmd.py
ovirtlago/__init__.py
ovirtlago/cmd.py

This fixes a small bug, when the 'reposync' configuration
was passed but didn't exist, the 'ovirt reposetup' command
failed.
fixes: https://github.com/lago-project/lago/issues/368

ovirtlago: allow running reposync with custom_sources only

---

lago/virt.py
lago/vm.py
ovirtlago/virt.py

This PR adds a 'cpu_model' parameter to the init file. If defined, it will generate the domain XML with that cpu_model, otherwise it will use the environment defaults. 
There will be 2 options to define the cpu model:
1. By defining it in the init file as noted above. 
2. By creating a new VM plugin and overriding the ``cpu_model`` property. This could allow to create more complex CPU model detections if needed.

Allow to define custom cpu model

---

ovirtlago/__init__.py
ovirtlago/cmd.py
ovirtlago/reposetup.py

1. Add optional '--repoman-config' option to ``lago ovirt reposetup``, this will allow overriding the defaults global configuration of repoman.
2. Don't download source RPMs in the default repoman configuration.
3. Allow passing custom **global** repoman filter, the default is still ``:only-missing``.
4. Remove old warning messages.

Custom repoman configuration

---

automation/check-merged.repos.el7
automation/check-patch.repos.el7
docs/Installation.rst
lago.spec.in

Lago requires qemu-kvm >= 2.1.2 and on centos/rhel those versions
are provided by qemu-kvm-ev.

Force usage of qemu-kvm-ev on centos/rhel

---

ovirtlago/virt.py

This reverts commit f31b74c44e7c1d3db61c85af3cfc59846c013751.
My mistake - I missed that we call this method in OST. 
We should  probably deprecate this method and instead call the prefix direct method, but this can be done later.

Revert "ovirtlago: drop get_ovirt_cpu_family"

---

ovirtlago/__init__.py
ovirtlago/cmd.py

This reverts commit 208bfc34051e6f6d6783e353c22868ff035ff7cd.
This patch needs rework because it adds filters to the "extra_source" file.
for example:
2017-01-17 19:55:04,604::INFO::repoman.cmd::Adding artifacts to the repo /home/jenkins/workspace/rhv_4.0_system-tests/ovirt-system-tests/deployment-rhv-suite-4.0/default/internal_repo
Traceback (most recent call last):
File "/bin/repoman", line 10, in <module>
sys.exit(main())
File "/usr/lib/python2.7/site-packages/repoman/cmd.py", line 416, in main
exit_code = do_add(args, config, repo)
File "/usr/lib/python2.7/site-packages/repoman/cmd.py", line 307, in do_add
repo.add_source(art_src.strip())
File "/usr/lib/python2.7/site-packages/repoman/common/repo.py", line 122, in add_source
with open(artifact_source.split(':', 1)[1]) as conf_file_fd: …

Revert "ovirtlago: allow passing custom repoman filters"

---

lago/cmd.py
setup.cfg
tests/functional/common.bash

This patch add support generate ansible hosts file, which reflect the hosts created by lago.
This will be usefull to integrate with Ansible instead of bash or python scripts.

Add command to generate ansible hosts file

---

lago.spec.in
tests/functional/fixtures/ovirt.runtest/suite.yaml
tests/functional/fixtures/snapshot/1host_1disk_list
tests/functional/fixtures/snapshot/1host_1disk_status
tests/functional/fixtures/snapshot/suite_1host_1disk.yaml
tests/functional/ovirt.basic.bats
tests/functional/ovirt.runtest.bats
tests/functional/snapshot.bats

1. Enable "cirros dhcp hack" only on tests that use it.
2. Switch tested VMs distros:
``ovirt.runtest``: fc23 -> fc24
``snapshot``: fc23 -> el7.3-base
effort to fix: https://github.com/lago-project/lago/issues/439

tests: functional tests fixes 

---

lago/vm.py

In situations where lago runs under a container(or mock),
we might bind-mount the images directory into the container,
and then the images might be in an unknown uid/gid, therefore it
is not safe to compare their uid's against the environment users
database. This patch ensures the check is safe. Note that if
the caller does not have sufficient privileges, it will fail(as needed).
closes: https://github.com/lago-project/lago/issues/447

safely check qemu uid after snapshot

---

lago.spec.in

Fix for https://github.com/lago-project/lago/issues/380
Note it will actually be fixed in the version after the version this PR gets in(because the old spec file would still remove the service in ``%preun`` stage)

ovirtlago-spec: fix firewalld ovirtlago service dropped on upgrade

---

lago/log_utils.py
lago/utils.py

This PR adds a uuid attribute to each LogTask class instance, and for each run_command. It allows to re-use the generated uuid in LogTask in run_command. This will allow to more easily debug long-running tasks, from the commit message:
```
This patch will generate a uuid and log it on each call to
'_run_command' method. It also allows to reuse an existing uuid.
This is useful in debugging long-running commands(such as repoman),
especially with the combination of hitting 'shift+*' while the cursor
is standing on the uuid(in VIM at least).
Example:
run_command(['ls', '-lsah'])
lago.log:
... ::DEBUG::start task:c62d45f1-bae6-40d7-95fa-277b0a5d6305:Run command: "ls" "-lsah":
... ::DEBUG::c62d45f1-bae6-40d7-95fa-277b0a5d6305: command exit with return code: 0
... …
```

add uuid to run_command and LogTask

---

automation/common.sh
lago/cmd.py
lago/export.py
lago/plugins/vm.py
lago/prefix.py
lago/templates.py
lago/utils.py
lago/virt.py
lago/vm.py
setup.cfg
tests/functional/common.bash
tests/functional/export.bats
tests/functional/fixtures/export/exported_suite.json
tests/functional/fixtures/export/repo_store/vm0_root.qcow2.hash
tests/functional/fixtures/export/store_skel/vm0_root.qcow2.hash
tests/functional/fixtures/export/store_skel/vm0_root.qcow2.metadata
tests/functional/fixtures/export/suite.json
tests/functional/fixtures/export/template_repo.json

1. Added the ability to export images from the current prefix,
either as  a layered image or as a base image (Lago will create a
new image which is a merge of the layer and its base).
When exporting the image as a layer, the path to his parent will
be replaced with the current directory, relative to the path of the
exported image (in simple words, it expect that the parent will be with
him in the same directory). All this logic can be found in export.py.
2. Added the ability to resolve the parent of a layered image
(for now only one level, and only for "template_type=qcow2").
Lago will check if the parent is in the cache, if not it will
download it from the template repo that was provided, and then
create a symlink from the layer's directory to the parent.
3. When using a file based disk, …

Added the ability to export images from a prefix

---

ovirtlago/__init__.py

This reverts:
commit bfea3cc4d104381cd6e5a2ffd9d325843f5ac5f0
Author: Yaniv Kaul <ykaul@redhat.com>
Date:   Wed Oct 5 12:02:11 2016 +0300
Continue testing on test failures.
It is better to fail than spam the log with further failures.

Revert bfea3cc4d104381cd6e5a2ffd9d325843f5ac5f0 - stop on failures

---

lago/dom_template.xml

Some images will need a video device to boot,
so adding a simple video device.

Adding basic video device

---

tests/functional/export.bats

1. Destroy layered env at the end of export functional
test.
2. Fixed some typos in the names of the export tests.

Destroy layered env at the end of the tests

---

lago/sysprep.py

during sysprep.
For the time being, no one is calling it - I'm using it manually
by modifying vm.py if I need to, but it's good to have it.

Allow to call sysprep.update() which will update all packages

---

lago/workdir.py
tests/unit/lago/test_workdir.py

On failure to find a workdir, look for the following patterns:
1. 'current_path/*/current'
2. 'current_path/*/.lago'
Then quickly evaluate for each one of them if they can be a workdir,
if so, append their truncated paths to the exception message, so the
user could change directory to there.
Fixes: https://github.com/lago-project/lago/issues/451

Print informative message when no workdir is found

---

lago/cmd.py

The above function relays on an higher version of python-setuptools
which is not available in EPEL. It seems, this was added in order be
more user friendly, and verify Lago's dependencies are installed.
However, requiring a custom-built python-setuptools for el7
installations is probably less friendly.
fixes: https://github.com/lago-project/lago/issues/468

Drop check_deps function

---

lago/cmd.py
lago/plugins/vm.py
lago/prefix.py
lago/utils.py
lago/virt.py
tests/functional/fixtures/snapshot/1host_1disk_list

The generated init file will represent the env and will contain
relative paths to the exported images.
closes https://github.com/lago-project/lago/issues/473

Generate an init file that can be used with exported images

---

lago/templates.py

Makes it easier to know where we tried to download from.

Print the URL if an IO error occurred.

---

lago/cmd.py
lago/plugins/vm.py
lago/prefix.py
lago/virt.py
lago/vm.py
setup.cfg

1. Adding lago shutdown - gracefully shutdown / reboot vm.
2. If acpi is enabled in the vm, use libvirt function, otherwise
try to run the command using ssh.
3. Change VirtEnv.get_vms to support filtering by name.
closes https://github.com/lago-project/lago/issues/464

Adding lago shutdown

---

lago.spec.in

This reverts commit 79249c14b6346a91764d5a532e2dd8afe5f46563.
1. CSB systems doesn't have those versions of paramiko.
2. We don't realy need a specific version of paramiko.

Revert "spec: require paramiko >= 1.16.1-2 on el7"

---

lago/prefix.py
lago/templates.py

Not sure why it's needed and where it's used.
Doesn't seem very useful.

Remove the whole marking of usage of templates

---

lago/dom_template.xml
lago/prefix.py
lago/vm.py

1. This in theory should improve performance. I did not measure much,
but I'm running in RAM / SSD, so can't expect much.
2. Hopefully virtio-console improves performance a bit over regular console.

Change lazy_refcounts to ON in the snapshots, move to virtio-console, add multiple queues to virtio-scsi

---

lago/net_nat_template.xml
lago/virt.py

This is a simple way to make sure we can use DHCP in multiple networks (with only one also served by DNS).

Let us control if DNS should be enabled in a libvirt network.

---

lago/vm.py

The previous timeout of 15 secondes wasn't enough
for shutting down loaded vms (such as ovirt-engine).

Increase shutdown timeout

---

ovirtlago/__init__.py
tests/functional/ovirt.runtest.bats

In order to support junit reports in all the projects in std ci,
we've changed the naming convension of junit reports to "*.junit.xml"

modified junit reports naming to match the standard ci convention

---

tests/functional/fixtures/ovirt.runtest/002_testlib.py
tests/functional/fixtures/ovirt.runtest/suite.yaml
tests/functional/ovirt.runtest.bats

1. Run a few "simple" prefix API calls, as used by OST.
2. Test 'cpu_model' definition. This is not strictly related to ovirtlago
but we better do this on a standard distribution(rather than
CirrOS), so in order not to make the tests longer, it is here.

tests: add prefix and cpu tests to ovirt.runtest

---

docs/requires.txt

New version was released.
This reverts commit 4d1cfc5c80081053cfe6bb6e0ffa1b4048fe4e15.

Revert "docs: pin sphinx version"

---

automation/common.sh

Had some unexplained errors. Was probably a mistake to remove it in the
first place.

automation: bring back libguestfs debug mode

---

lago/cmd.py
lago/export.py
lago/plugins/vm.py
lago/prefix.py
lago/providers/libvirt/network.py
lago/providers/libvirt/vm.py
lago/ssh.py
lago/sysprep.py
lago/templates.py
lago/utils.py
lago_template_repo/__init__.py
ovirtlago/cmd.py
ovirtlago/virt.py
scripts/version_manager.py
setup.py
tests/unit/lago/providers/libvirt/test_cpu.py
tests/unit/lago/test_workdir.py
tests/unit/test_config.py

This brings us back in line with the most recent yapf auto-formatting
style, covering up for the time we pinned it(d891034b) and unpinned
it(e5c3b959)

yapf: new version code formatting fixes

---

lago/cmd.py
lago/export.py
lago/plugins/vm.py
lago/prefix.py
lago/providers/libvirt/network.py
lago/providers/libvirt/templates/net_nat_template.xml
lago/providers/libvirt/vm.py
lago/ssh.py
lago/sysprep.py
lago/templates.py
lago/utils.py
lago_template_repo/__init__.py
ovirtlago/cmd.py
ovirtlago/virt.py
scripts/version_manager.py
setup.py
tests/functional/fixtures/start/expected_up_status
tests/unit/lago/providers/libvirt/test_cpu.py
tests/unit/lago/test_prefix.py
tests/unit/lago/test_workdir.py
tests/unit/test_config.py

1. Select a network to serve as a central DNS server, by the following logic:
- if it is the only network defined in the init file, else;
- the only management network defined in the init file, else;
- if there is more than one management network, use the one with DNS
configuration in the init file; else;
- if there is no DNS configuration, choose the first management network found.
Corner cases such as defining DNS for two different 'management'
networks are not allowed and will throw an error on 'lago init'.
2. Once the network is chosen, all DNS records will be configured in it,
all other networks will forward the requests to it.
3. Custom DNS records can also be defined in the init file, by adding
'dns_records' in the network that has DNS configuration.

Move to a single DNS server per management network 

---

lago/log_utils.py
lago/utils.py
tests/unit/lago/test_log_utils.py

1. sys.exc_info returns the last exception that was caught,
this can confuse LogTask and make it print messages on exceptions that
were already handled and don't interupt to the flow of lago,
(for example when waiting for ssh).
Insted we will use the default arguments which are being passed
to __exit__, and reflects the last exception that was thrown and not handled.
2. If an error occurred, print that stack trace in LogTask.

Stop using sys.exc_info in LogTask

---

lago/build.py
lago/cmd.py
lago/prefix.py
tests/functional/fixtures/snapshot/1host_1disk_list
tests/unit/lago/test_build.py

This commit adds the ability to customize vm images
during init phase.
Currently only "virt-sysprep" is supported.
For each disk that need customization, the command name and
arguments should be specified in the init file.

Adding the abilty to customize images during init

---

ovirtlago/cmd.py
ovirtlago/utils.py
ovirtlago/virt.py

In 'lago ovirt start', before making any API calls, assert that
ovirt-engine and vdsmd services report running on all hosts. Note that
the time includes the time we have to wait for the VMs to be up(and
sshd) available, and the time for the services to come up.
fixes: https://github.com/lago-project/lago/issues/508
and probably other sporadic issues.

ovirtlago: assert ovirt-engine and vdsmd services are running

---

lago/virt.py

Adding the ability to specify whether to perform
bootstrap on a given domain or not.
This will be done by adding the 'bootstrap' key and
boolean value to the domain definition.
The default will be to run bootstrap.
Init switch '--skip-bootstrap' has precedence over the
configuration in the init file.

Control bootstrap in the init file

---

lago/prefix.py
lago/providers/libvirt/network.py
lago/utils.py
lago/virt.py

Commit 6386bc8 relays on DNS records stored in the Prefix metadata.
This commit ensures that environments which were initialized prior
to that commit, will work as before.

 Make DNS changes introduced in 6386bc8 backward compatible

---

lago/providers/libvirt/templates/dom_template-el6.xml
lago/providers/libvirt/vm.py

The idea is to "freeze" the el6 template, so we won't be breaking stuff when adding new features to the "upstream" template. Specifically for now, set the console back to 'serial'.
Fixes: https://github.com/lago-project/lago/issues/504

Use a seperate template for el6

---

ovirtlago/cmd.py
ovirtlago/virt.py

ovirtlago: reconfigure timeouts in 'lago ovirt start'
1. Increased default timeout for waiting until the VMs connected
to the Engine report 'up' status to 8 minutes.
2. Added '--vms-timeout' parameter to allow configuring that timeout.
3. Increased 'ovirt-engine'/'vdsmd' service timeout to 3 minutes.
4. Added default timeouts in all relevant functions headers, and set
the timeouts explicitly in 'do_ovirt_start' for visibility.

ovirtlago: change --with-vms timeout in 'lago ovirt start' to 8 minutes

---

ovirtlago/cmd.py

The message will include the url to the web UI, username and password.

Print informative message after "lago ovirt start"

---

lago/virt.py

Until https://github.com/lago-project/lago/issues/524 will be solved, removing dns entries from the exported init file.

Remove dns entries from exported init file

---

Makefile
automation/check-patch.sh
automation/common.sh
test-requires.txt

1. Add coverage.py test results
2. Export coverage.py results and unit tests as xunit XML

tests: add coverage.py report and export results XML

---

tests/unit/lago/test_prefix.py

Small issue.
The exception was asserted over 'net-1, net-2,' pattern, while
it could be 'net-2, net-1'. So switching to a regex instead.

tests: fix ordering in TestPrefixNetworkInitalization

---

tests/unit/lago/test_utils.py

Similar issue to 6852bf6f, the ordering of the elements in the dict was
not promised, using OrderedDict instead.

tests: fix test_nested_mixed

---

lago/log_utils.py
lago/sdk.py
test-requires.txt
tests/functional-sdk/conftest.py
tests/functional-sdk/test_sdk_sanity.py
tests/unit/lago/conftest.py
tests/unit/lago/test_prefix.py
tests/unit/lago/test_sdk.py
tests/unit/lago/test_workdir.py
tests/unit/lago/utils.py
tox-sdk.ini

1. Now the 'normal' prefix/logs/lago.log works under the SDK too.
2. Added 'add_stream_logger', which allows to easily
debug interactive sessions.
3. Allow to add a per env logfile by passing a logfile parameter
to sdk.init

 sdk: add logging options

---

lago/prefix.py

Verified it is working as expected, specifically for the environment
variables.

sdk: added 'deploy' to exposed methods

---

lago/providers/libvirt/vm.py
lago/sysprep.py

1. In debian, the network scripts are found in:
``/etc/network/interfaces``
And per-interfaces configurations can be loaded from:
``/etc/network/interfaces.d/``
In Ubuntu 16.04, the naming scheme changed, (eth -> ens), however, it
can still be configured by updating the kernel parameters in grub, which is what 
we'll do for now when building the images. So keeping 'eth' convention for debian. Although
this is *probably* not the best thing to do(go backwards with the interface names),
But changing the interfaces names in our sysprep methods would make
the code more complex, and I rather first implement https://github.com/lago-project/lago/issues/516.
* Note that this does not allow NetworkManager to configure the
interfaces, however, Ubuntu 16.04 does not come with it pre-installed with …

 sysprep: support debian network scripts locations

---

lago/sysprep.py

Was accidentally removed in 24994fca.

sysprep: add back escaping to network setup scripts

---

automation/check-merged.sh
automation/check-patch.sh
automation/common.sh
docs/docs-requires.txt
test-requires.txt
tests/functional-sdk/conftest.py
tests/functional-sdk/test_sdk_sanity.py
tox-sdk.ini

1. On check-merged, run a multi-distro tests, to check
most images which are on templates.ovirt.org are functional, including
interconnectivity test.
2. Don't run again tests that already ran in 'check-patch'. In our
current merging flow, you always have to rebase, so the patch being
merged - must have passed check-patch.

tests: add check-merged functional sdk tests

---

automation/check-patch.packages
automation/check-patch.packages.el7
lago/plugins/vm.py
lago/sdk.py
lago/ssh.py
tests/functional-sdk/test_sdk_sanity.py

1. Add ansible inventory methods to the SDK, those are just delegated to ``lago_ansible.py``.
2. Add basic ansible tests on 'check-merged. 
3. Fix 2 SSH bugs discovered during the process(in different commits).

 sdk: added ansible inventory methods 

---

lago/providers/libvirt/templates/dom_template.xml

The use of /dev/urandom instead of /dev/random accelerates the
ovirt-system-tests. On local verification this change saves
6 minutes of execution time for basic-suite-4.1.
Signed-off-by: Dominik Holler <dholler@redhat.com>

templates: Use /dev/urandom for RNG

---

lago/providers/libvirt/vm.py
lago/sysprep.py

It is used to disable services to boot faster: kdump and postfix.
Specifically disabling kdump reduces boot time nicely.

Add the '--delete' to sysprep so we can delete files during sysprep.

---

lago/build.py
tests/unit/lago/test_build.py

1. Allow specifying a list of arguments to an option of a build command.
2. Print the build command structure when running in loglevel=DEBUG.
3. Added a test for this change.

build: Allow to use a list of arguments

---

automation/check-patch.packages
automation/check-patch.packages.el7
lago.spec.in
lago/providers/libvirt/vm.py
lago/sysprep.py
lago/templates/sysprep-base.j2
lago/templates/sysprep-debian.j2
lago/templates/sysprep-el6.j2
lago/templates/sysprep-el7.j2
lago/templates/sysprep-fc24.j2
lago/templates/sysprep-fc25.j2
lago/templates/sysprep-fc26.j2
lago/templates/sysprep-macros.j2
requirements.txt
test-requires.txt
tests/unit/lago/test_sysprep.py

Shifting the sysprep logic to Jinja2 templates, and calling 'sysprep' with the generated file. This allows splitting the logic to different distros, re-use templates where applicable and most importantly - makes it easier to maintain. 
How it works
-----------------
On bootstrap stage, we try to load ``template/sysprep-{distro}.j2`` template. If it is not available, we load ``templates/sysprep-base.j2``. Each template can include the base one(currently all do).
The structure of templates directory is:
```bash
$ tree templates
templates
├── sysprep-base.j2
├── sysprep-debian.j2
├── sysprep-el6.j2
├── sysprep-el7.j2
├── sysprep-fc24.j2
├── sysprep-fc25.j2
├── sysprep-fc26.j2
└── sysprep-macros.j2
```
Where except the distro specific templates, ``sysprep-macros.j2`` includes some useful …

 Move sysprep to Jinja2 templates 

---

lago/ssh.py

This seems to fix the usage of SSH for VMs without public key.
On the way, it simplifies the code a bit.

Fix SSH for VMs without public key

---

lago.spec.in
lago/prefix.py
lago/subnet_lease.py
requirements.txt
tests/unit/lago/test_subnet_lease.py

The general idea of how to manage the store has not
changed, but the following changes were made:
1. Created a 'SubnetStore' class which represents the store.
(it makes unit testing easier)
2. Created a 'Lease' class which represents a lease file in the store.
3. Allow requesting a specific lease from the store.
4. Increased the range of the store to 192.168.200.0-192.168.255.0
5. Use 'netaddr' to validate and represent ip addresses.
6. Improved exception handling.
7. Added unit tests.
closes https://github.com/lago-project/lago/issues/530
closes https://github.com/lago-project/lago/issues/523
closes https://github.com/lago-project/lago/issues/454

Refactor subnet lease

---

tox-sdk.ini

1. Always operate in debug mode
2. Increase appliance memory size per BZ 1418283

tests: configure libguestfs parameters for sdk tests

---

lago/plugins/vm.py

1. Search for the substring, as it might not be in the end.
2. Extract the exception message safely.
3. Re-raise the original exception on all other cases.
Fixes: https://github.com/lago-project/lago/issues/580

collect: search 'No such file or directory' errors properly

---

lago.spec.in
lago/providers/libvirt/templates/dom_template-base.xml.j2
lago/providers/libvirt/templates/dom_template-el6.xml.j2
lago/providers/libvirt/utils.py
lago/providers/libvirt/vm.py

1. Move domain templates to Jinja2, for now only for simple replacements, so there is not a big difference
from what we had before.
2.  Use /dev/random on libvirt versions <= 2002001
A small change comparing to https://github.com/lago-project/lago/pull/554 (currently rebased on it)
fixes: https://github.com/lago-project/lago/issues/572
fixes: https://github.com/lago-project/lago/issues/516

Move domain templates to Jinja2

---

lago/utils.py

Information about locks is irrelevant to the user,
so moving it to debug level.

Change the log level of LockFile cm

---

lago/templates/sysprep-macros.j2

Typo, though functionality wise didn't notice any failures.

sysprep: add spaces in Jinja2 macro templates

---

automation/build-artifacts.sh
automation/common.sh
tox.ini

1. First build the sdist to exported-artifacts.
2. Then build the RPMs(which also create an sdist - but manipulate it).
3. Add installation test from the sdist we exported(and don't let tox
produce it by itself, because that is not the one we publish).
4. Lastly, don't publish the 'tar.gz' the RPMs used, only the sdist.
This avoids the corruption in the sdist that our RPM related scripts
caused(in Makefile). So we ensure the 'sdist' we publish is the one
produced by 'python setup.py sdist'.

Fix sdist creation

---

lago/__init__.py
lago/guestfs_tools.py
lago/plugins/vm.py
lago/providers/libvirt/vm.py
lago/validation.py
tests/functional-sdk/test_sdk_sanity.py

1. Extract all current functionality to lago/guestfs_tools.py, so we'll
have `import guestfs` only there.
2. Add an explicit method to extract files with guestfs:
extract_paths_dead
3. Add some ugly checks if guestfs is available and throw exceptions
when needed.
4. Add a functional SDK test for `extract_paths/extract_paths_dead`
As a side note, I should say that I think we should refactor the "VM Provider" and "VM Plugin" concept, to something more maintainable and easier to extend. Theoretically I had to add one method(extract_paths_dead) to the libvirt provider. Practically, it required me to add it 3 places, either as an abstract method or as a proxy. And even with that - we don't even get the proper docstrings of the function(as it is proxied).
Signed-off-by: Nadav Goldin …

 Make Lago operational without 'guestfs' module

---

lago/providers/libvirt/vm.py

In f8be8f4d892149669c9f1abc4bdaf67cc9a5ae2c I misused 'getVersion'
instead of 'getLibVersion'. The first returns the hypervisor version
which was not the intention.
Tested locally where it matters: started with lago a Ubuntu 16.04 VM -> installed Lago from pip -> started a el7.3 nested VM.

Get libvirt version correctly

---

lago/cmd.py
lago/export.py
lago/plugins/vm.py
lago/prefix.py
lago/providers/libvirt/vm.py
lago/utils.py
lago/virt.py

1. Allow to specify in the init file which vms / disks to export.
2. Don't run virt-sparsify on iso disks.
3. Use deepcopy when generating the env's spec (will help
to avoid unwanted changes to the internal metadata of the env).
4. Adding collect only option to export cmd: This option will output
the mapping from vms to the disks that will be exported.
5. Expose export to lago.sdk
6. Safely try to parse the name of the backing image:
Due to lago image store naming convention (repo:image:version),
if the backing image is a Lago image, preprocessing to the name
needs to be done (in order to extract only the image name and the
version) and then set it as the backing image of the exported image.
Since not always the backing image will be a Lago images, adding
exception handling to the parsing …

export: Some fixes

---

docs/Installation.rst

1. Ubuntu 16.04 installation instructions:
With regard to debian vs ubuntu: looks like debian 8 will not work as it has an old version of libguestfs (v1.28), so debian 9 will probably work, but I don't have a VM to test it on at the moment.
If anyone wants to give it a try:
Create ``init-ubu.yaml``:
```yaml
domains:
ubu:
memory: 2048
nics:
- net: net01
disks:
- template_name: ubuntu16.04-base
type: template
name: root
dev: sda
format: qcow2
- name: data
type: empty
format: qcow2
size: 50G
dev: sdb
metadata:
deploy-scripts:
- $LAGO_INITFILE_PATH/install_lago_debian.sh
artifacts:
- /var/log
nets:
net01:
type: nat
dhcp:
start: 100
end: 254
management: true
dns_domain_name: lago.local
```
Create ``install_lago_debian.sh`` in the same dir:
```
#!/bin/bash -ex
readonly DUMMY_USER="koko"
apt-get …
```

docs: add Ubuntu 16.04 pip installation notes

---

lago.spec.in

Older versions don't have '--commands-from-file' which we use now
by default.

spec: force libguestfs >= 1.30

---

lago/plugins/__init__.py

closes https://github.com/lago-project/lago/issues/607

Print warning when failed to load plugin

---

lago/guestfs_tools.py
tests/functional-sdk/test_sdk_sanity.py
tests/functional-sdk/utils.py
tests/functional/collect.bats
tests/unit/lago/test_guestfs_tools.py

1. Fixed a bug where the exception would not be re-raised after max
attempts exceeded to remount.
2. Changed re-trying logic to restart the connection, as needed.
3. Added a context manager for the guestfs connection, decoupling the
functions.
4. Added unit tests and enhanced the SDK functional tests to use some
randomly generated directories
fixes: https://github.com/lago-project/lago/issues/629

guestfs: refactoring

---

automation/check-patch.packages
automation/check-patch.packages.el7

1. libguestfs-devel was twice on the list.
2. virtualenv, and tox are being installed before running the
tests (using pip).
3. For some reason when installing tox from rpm, entry points aren't
created, and then the job failed on 'tox: Command not found'. This
patch will ensure that tox is always installed from PyPi.
Fixes: http://jenkins.ovirt.org/job/lago_master_github_check-patch-fc26-x86_64/216/console

Automation: Remove duplicate packages from mock *.packages

---

lago/cmd.py

Don't see any real usage for it anymore, especially when you can install
directly from pip without Lago group.

cmd: drop group warning

---

scripts/check_style.sh

In yapf 0.17 the diff command returns non 0 code
if there is a different between the given files, and the output
of the formatter. Adjust to this change.

style: Adjust to yapf 0.17

---

docs/Installation.rst

Adding troubleshooting information about how to fix
IPv6 configuration error that occurs with latest versions of libvirt.

docs: Troubleshooting IPv6 accept_ra error

---

.style.yapf
lago/build.py
lago/cmd.py
lago/guestfs_tools.py
lago/lago_ansible.py
lago/plugins/vm.py
lago/prefix.py
lago/providers/libvirt/network.py
lago/providers/libvirt/vm.py
lago/ssh.py
lago/sysprep.py
lago/templates.py
lago/utils.py
lago/virt.py
setup.cfg

1. Latest releases of yapf (specifically 0.17) introduced some bug
fixes which effect the formatting of the code. In this commit the
code is reformatted with the latest version of yapf.
2. Added a new style rule: each list of arguments which is bigger than 1
and ended with a comma will be split into multiple lines.

style: Format code with yapf 0.19

---

lago/providers/libvirt/network.py
lago/templates/sysprep-macros.j2

This allows us to test with Jumbo frames.
Hopefully, it'll also generally improve performance
(NFS, iSCSI traffic, etc.)
I *think* it won't break if lower libvirt is used.
It won't set the MTU, and ifcfg-* value will be ignored.

Set MTU for all interfaces to 9000.

---

lago/providers/libvirt/templates/dom_template-base.xml.j2
lago/providers/libvirt/vm.py

1. Set only the 1st disk as bootable.
2. Don't advertise PM support to the guest - we don't use it anyway.
3. Don't use serial console for boot - we don't use it anyway.

Small changes to the libvirt XML

---

lago/cmd.py
lago/utils.py

This PR should fix https://github.com/lago-project/lago/issues/669 by catching SIGTERM and thus require cleanup actions.

Exit gracefully on SIGTERM

---

tests/functional-sdk/test_sdk_sanity.py

Add a test for checking if a VM is running.
Make sense to verify that the VMs are running before
testing ssh.

sdk_tests: Check that VM is running

---

lago/prefix.py
lago/providers/libvirt/vm.py
tests/unit/lago/test_prefix.py

Apparently, it's not enough to set it for the network.
It needs to be set up per the interface as well.
For example:
nics:
- net: lago-{{ env.suite_name}}-net-management
- net: lago-{{ env.suite_name}}-net-storage
mtu: 9000
Would set MTU 9000 to net-storage.
(It should match the network too!)

Set MTU per interface.

---

lago/ssh.py

only if the 1st connection failed and we retry.
It's just annoying to see it on every SSH connection.

Switch the log of SSH retries to display

---

tests/functional-sdk/test_sdk_sanity.py

Disable the test until we will figure out why it's unstable
in CI.

sdk-functional: Disable extract_paths_dead test

---

lago/prefix.py

If ssh isn't available, sleep 10 seconds before running "wait_for_ssh".
This condition will reduce cpu and log messages when running "lago
deploy".

deploy: Sleep 10 seconds if ssh isn't available

---

lago/prefix.py

This commit is part of 167d99a.
Without it, if host.ssh_reachable() is false, the outer log
task will always be marked as a failure.

deploy: Don't propagate fail when waiting for ssh

---

lago/utils.py

1. Adding missing call to 'format'.
2. Make log messages more accurate.

utils: Lock CM improve log messages

---

test-requires.txt

- It will save us to format the entire code base every couple
of month when a new version of yapf is released.
- Pin yapf to version 0.20

style: Control manually on yapf version

---

docs/conf.py

Mock future lib when building the docs.
This way sphinx will not complain that it's missing.

docs: Mock future lib

---

lago/cmd.py
lago/paths.py
lago/prefix.py

- Expose Paths object in the SDK (currently, we can only expose methods,
not properties).
- Expose the paths attribute as a property (for internal use inside lago).
- Added some documentation about the Paths class.
- In Prefix class, change the attribute name that contains the prefix path from
"prefix" to "prefix_path" (the convention in our code is that a variable
named "prefix" is a Prefix object).
- Remove "_prefix" attribute from the prefix object. This attribute
used to hold the path to the prefix, but the same value is also stored
in the Paths object, so there is no reason to save it twice.

prefix: Expose Paths object in the SDK

---

lago/brctl.py

The interface of "brctl" was changed in fc27.
When calling "brctl show X", if X doesn't exists,
the return code is non-zero. In order to overcome this issue,
check if the bridge exists using "ip" command.

brctl: Use "ip" to check if a bridge exists

---

lago/cmd.py

Ther is no reason to fail 'lago init' if a user want
to create the workdir in an existing directory.

Allow to create a workdir in an existing dir

---

tests/functional-sdk/conftest.py
tests/functional-sdk/lago_fixtures.py
tests/functional-sdk/test_sdk_sanity.py

sdk-tests: Update the test's images
- We have a new image of el7.4
- fc25 is obsolete
sdk-tests: Move Lago's fixtures to an external module
This way Lago's fixtures can be shared across different
test modules.

SDK functional move fixtures and update images

---

lago/providers/libvirt/network.py

We only need really one entry per host.
The fact a host has many DNS names (X-eth..., X-<network-name>, etc...)
doesn't mean we need so many DHCP entries.

Reduce the number of DHCP entries we add to libvirt.

---

lago/plugins/vm.py

check_alive decorator raise RuntimeError if the vm is not running.
The API of ssh_reachable defines that "False" should be returned if the
vm is not ssh reachable (which is the case when the vm is not running).

Don't use check_alive decorator in ssh_reachable

---

lago/cmd.py
lago/plugins/vm.py
lago/providers/libvirt/network.py
lago/providers/libvirt/utils.py
lago/providers/libvirt/vm.py
lago/virt.py
tests/functional-sdk/test_sdk_sanity.py

Less calls (hopefully) to libvirt, more specific lookups for VMs
and networks.
A bit of cleanup - remove of libvirt related stuff from lago/virt.py

libvirt calls cleanup

---

lago/plugins/vm.py
lago/ssh.py

Use custom exception in "get_ssh_client"
If there was a failure to get a connected ssh client, raise
"LagoSSHTimeoutException". This change will make it safer to catch
exceptions raised by "get_ssh_client".
Add docstrings to "get_ssh_client"

Update get ssh client

---

automation/common.sh

Up until now we used to trigger lago's functional tests with the lago
group.
This can cause an issue if the lago group doesn't exist on the host that
runs the mock. Also, this is not really testing anything, since we run as
root inside the mock.
In order to test the creation of the lago group, tests can be run in
"lago-demo" repository, which uses VMs for running the tests.

cli-functional-tests: Don't use lago's group

---

lago/plugins/vm.py
lago/providers/libvirt/utils.py
lago/providers/libvirt/vm.py
lago/vm.py

We ask the provider for the state of the VM, so it makes
sense to also ask the provider if the VM is running.
- Don't list all the VMs, just lookup the VM that is associated
with the provider.
- Handle edge cases where an unknown state was returned from Libvirt,
or when the VM doesn't exist.
closes https://github.com/lago-project/lago/issues/492

Ask the provider if the vm is running

---

lago/vm.py

Some of the arguments that being passed to "get_ssh_client"
should be taken from the VM object and not from the provider.

Fix "running" method in SSHVMProvider

---

lago/cmd.py

It will make debugging easier.

Print Lago* exceptions' stack trace to lago.log

---

tests/functional-sdk/conftest.py

During the functional tests, the VM with this image boots
without a network. Due to a bug in libguestfs, we can't
collect logs from a VM without a network connection, so debugging should
be done manually.
Until we sort this out, remove this image from the functional tests in
order to not block other PRs.

Remove debian8 image from functional tests

---

lago/cmd.py
lago/prefix.py
lago/utils.py

This change will improve the way we show errors to the user.
Most of the times, there is no need to expose the low level details of
an exception to the user. If needed, the information can be printed
explicitly.
Use a custom exception if the invocation of the deploy scripts fails.
This change will hide the traceback from the user, while keeping
the stderr of the script.
Error messages should be printed with the ERROR log level.

Improve error reporting

---

lago/plugins/__init__.py
lago/prefix.py
test-requires.txt
tests/functional-sdk/conftest.py
tests/functional-sdk/test_sdk_sanity.py
tox.ini

This change will eliminate CI failures due to a change
in Flake8 version.
Flake8 version update should be manageable.
Without setting the locale the build is failing with:
```
locale.setlocale(locale.LC_ALL, '')
locale.Error: unsupported locale setting
```
setuptools (which is used by stevedore) 11.3 deprecated the required flag
to load() in favor of two new methods.
A fix was introduced in stevedore 1.2.0.
Since we are using and older version of stevedore (0.14) from epel,
lago outputs the deprecation warning, which isn't helpful for our users.
A long term solution will be to use a newer version of stevedore, but
currently it only available in Openstack repos.
OpenSSH-7.8 introudced a new key format which isn't supported by
paramiko [1]. Use PEM key format instead.
We have not seen this …

Fix build errors

---

lago.spec.in
lago/subnet_lease.py
lago/templates.py
lago/utils.py
requirements.txt
tests/unit/lago/test_lock.py
tests/unit/lago/test_subnet_lease.py

The current locking method leaves stale lock when Lago
is being terminated using SIGKILL.
Using flock we can overcome this issue.
Also:
1. Make FileLock context manager more generic.
2. Add a test.
3. Adjust templates.py - we don't use the "_lock" decorator.

Change file locking method to flock

---

docs/docs-requires.txt
lago/providers/libvirt/vm.py
lago/templates.py
test-requires.txt
tests/functional-sdk/conftest.py

* `sha1` is [already a digest](https://github.com/pilou-/lago/blob/cb6a8d0295d89a9cea848fcd52ac25e80aad3b36/lago/utils.py#L745). Error was:
AttributeError: 'str' object has no attribute 'hexdigest'
* Fix the CI:
* `nbsphinx` version: `nonlocal` statement is [used since 0.4.0](https://github.com/spatialaudio/nbsphinx/blob/11a6e4da3eadc1a4dda189e4fcc1685853665f08/src/nbsphinx.py#L1088) and [breaks Python 2 compatibility](https://jenkins.ovirt.org/blue/organizations/jenkins/lago_master_github_check-patch-el7-x86_64/detail/lago_master_github_check-patch-el7-x86_64/972/pipeline#log-1040): exclude incompatible `nbsphinx` versions.
* use `get_closest_mark` instead of `get_marker`: `get_closest_mark` is [available since pytest 3.6.0](https://github.com/pytest-dev/pytest/blame/3.6.0/CHANGELOG.rst#L …

Remove erroneous call to hexdigest method

---

lago/plugins/output.py
tests/functional/fixtures/status/prefix_skel/expected.yaml

- Block style is more readable.
- Setting the style explicitly in Lago will make the output
deterministic (not dependent on python yaml defaults).

out-format: Always print yaml in block style

---

container/el7-systemd-lago/deploy.sh

Currently yum's return code for installing more than one package
at a time with the "-y" flag is successful if at least one
installation was successful - thus not throwing an error if any
package was skipped.
Adding the --setopt=skip_missing_names_on_install=False flag
solves this issue.
Source https://bugzilla.redhat.com/show_bug.cgi?id=1274211

Throw error if yum install failed in deploy.sh

---

lago.spec.in
lago/plugins/vm.py
lago/utils.py
tests/unit/lago/test_utils.py

Using 'scp' to copy a lot of data in a file-by-file manner is very
inefficient. This patch changes the way path extraction works:
- it creates a tar.gz archive containing all desired files on remote side
- uses ssh to redirect the output of tar|gzip pipe directly to local side (there are no files created on the remote side)
- extracts .tar.gz file to a temporary directory on the local side
- moves all the extracted files from temporary directory to target destination, at the same time renaming them to desired names
This algorithm offers drastic speed-ups when dealing with collection of a large dataset i.e. for oVirt System Tests, it reduces the time needed to collect artifacts from ~20 secs to ~2 secs. This in turn, trims down the running time of each OST suite by a couple of minutes.

Extract paths reimplementation

---

lago/utils.py

Explicitly set the permissions of lock files, thus even if umask other
then '0002' is configured, different users in the lago group can try to
acquire the lock.

Set file permissions on lock files

---

tests/unit/lago/test_config.py

When a developer has a '$HOME/.config/lago/lago.conf' config file
defined, 1:1 configuration comparisons fail - 'ConfigLoad' will add
configuration elements found in the file. This patch uses 'mock.patch'
to trick tests into thinking, that there are no user-defined
configuration files.
Signed-off-by: Marcin Sobczyk <msobczyk@redhat.com>

tests: Fix config tests for non-standard config

---

lago/log_utils.py

Don't compare log level with `LogRecord` instance, use `levelno` attribute instead.
Can be tested using this snippet:
>>> from logging import LogRecord, DEBUG, INFO
>>> DEBUG, INFO
(10, 20)
>>> LogRecord(None, DEBUG, None, None, "msg", None, None) >= INFO
True
>>> LogRecord(None, DEBUG, None, None, "msg", None, None).levelno >= INFO
False

Fix comparison between "LogRecord" and "level"

---

lago/log_utils.py

First parameter must be the current class, not the parent.

Fix 'super' usage

---

automation/check-patch.packages
lago/providers/libvirt/cpu.py
tests/unit/lago/providers/libvirt/fixtures/cpu_map/index.xml
tests/unit/lago/providers/libvirt/fixtures/cpu_map/x86_Penryn.xml
tests/unit/lago/providers/libvirt/test_cpu.py

On fedora29 the tox is failing   docs: could not install deps
Signed-off-by: Galit <grosenth@redhat.com>

Fix failure in running tox -e docs

---

automation/check-patch.packages.el7
requirements.txt
test-requires.txt
tox-sdk.ini
tox.ini

Both libvirt and libguestfs python libraries are tightly coupled
with their C equivalents. We cannot use arbitrary versions of those
libs from PyPI - we need to stick to the ones provided by the distro.
Signed-off-by: Marcin Sobczyk <msobczyk@redhat.com>

ci: Move libvirt and libguestfs deps to RPM level

---

lago/prefix.py

This PR adds a fix for libvirt 6 that requires backing file formats to be specified explicitly and support for relative backing file paths to lago.

Fixes in 'prefix' module
